services:
  autoware-monolithic:
    container_name: autoware-monolithic
    image: ghcr.io/autowarefoundation/autoware:universe-cuda
    volumes:
      - $HOME/autoware_map/sample-map-rosbag:/autoware_map:ro
      - $HOME/autoware_data:/root/autoware_data
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: |
      ros2 launch autoware_launch logging_simulator.launch.xml
      map_path:=/autoware_map
      vehicle_model:=sample_vehicle
      sensor_model:=sample_sensor_kit
      rviz:=false

  visualizer:
    container_name: visualizer
    image: ghcr.io/autowarefoundation/autoware-tools:visualizer
    ports:
      - 6080:6080
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

  rosbag:
    container_name: autoware-rosbag
    image: ghcr.io/autowarefoundation/autoware:universe
    volumes:
      - $HOME/autoware_map/sample-rosbag:/autoware_map/rosbag
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    command: |
      bash -c "export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp && sleep 5 && ros2 bag play /autoware_map/rosbag -r 0.2 -s sqlite3"
