services:
  autoware-monolithic:
    container_name: autoware-monolithic
    image: ghcr.io/autowarefoundation/autoware:universe-cuda-20251118
    volumes:
      - $HOME/autoware_map/sample-map-rosbag:/autoware_map:ro
      - $HOME/autoware_data:/root/autoware_data
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=:1
    runtime: nvidia
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    command: |
      ros2 launch autoware_launch logging_simulator.launch.xml
      map_path:=/autoware_map
      vehicle_model:=sample_vehicle
      sensor_model:=sample_sensor_kit
      rviz:=true

  visualizer:
    container_name: autoware-visualizer
    image: ghcr.io/autowarefoundation/autoware-tools:visualizer-20251118
    ports:
      - 6080:6080
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

  rosbag:
    container_name: autoware-rosbag
    image: ghcr.io/autowarefoundation/autoware:universe
    volumes:
      - $HOME/autoware_map/sample-rosbag:/autoware_map/rosbag
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    command: |
      ros2 bag play /autoware_map/rosbag -r 0.4 -s sqlite3
    profiles:
      - rosbag
