services:
  autoware-monolithic:
    container_name: autoware-monolithic
    image: ghcr.io/autowarefoundation/autoware:universe
    volumes:
      - $HOME/autoware_map/sample-map-planning:/autoware_map
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    command: |
      ros2 launch autoware_launch planning_simulator.launch.xml
      map_path:=/autoware_map
      vehicle_model:=sample_vehicle
      sensor_model:=sample_sensor_kit
      rviz:=false

  visualizer:
    container_name: autoware-visualizer
    image: ghcr.io/autowarefoundation/autoware-tools:visualizer
    ports:
      - 6080:6080
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
