services:
  autoware-monolithic:
    image: ghcr.io/autowarefoundation/autoware:universe
    volumes:
      - ../mount/kashiwanoha_map:/autoware_map
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    command: |
      ros2 launch autoware_launch planning_simulator.launch.xml
      map_path:=/autoware_map
      vehicle_model:=sample_vehicle
      sensor_model:=sample_sensor_kit
      scenario_simulation:=true
      rviz:=false
      
  visualizer:
    image: ghcr.io/autowarefoundation/autoware-tools:visualizer
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    ports:
      - 6080:6080
